language: ruby
rvm:
  - "2.0.0"
  - "1.9.3"
  - "1.9.2"
  - "1.8.7"
  - jruby-19mode
  - jruby-18mode
  - rbx-19mode

# Not sure what happened here, but this is reliably failing
#  - rbx-18mode

gemfile:
  - will_paginate.rails31.gemfile
  - will_paginate.rails32.gemfile
  - kaminari.rails31.gemfile
  - kaminari.rails32.gemfile
  - no_paginator.rails31.gemfile
  - no_paginator.rails32.gemfile

# The will_paginate gem won't even install in these modes :-(
matrix:
  exclude:
    - rvm: jruby-19mode
      gemfile: will_paginate.rails31.gemfile
    - rvm: jruby-19mode
      gemfile: will_paginate.rails32.gemfile
